sudo: required

language: python

matrix: 
    include:
    - python: "3.5"
      env: TEST_PRECOMMIT=true TEST_CODE=false
    - python: "3.5"
      env: TEST_CODE=true TEST_PRECOMMIT=false
    - python: "3.6"
      env: TEST_CODE=true TEST_PRECOMMIT=false
    - python: "3.7"
      env: TEST_CODE=true TEST_PRECOMMIT=false
    - python: "3.8"
      env: TEST_CODE=true TEST_PRECOMMIT=false

cache: pip

notifications:
    email:
        on_success: never
        on_failure: always

addons:
    apt:
        packages:
            - curl
            - gfortran
            - libblas-dev
            - liblapack-dev 

before_install:
    - pip install --upgrade pip setuptools

install:
    - pip install -r optional-requirements.txt
    - if [ "$TEST_CODE" == "true" ] ; then pip install -e . ; fi
    - if [ "$TEST_PRECOMMIT" == "true" ] ; then pip install -e .[dev] ; fi

script:
    - if [ "$TEST_PRECOMMIT" == "true" ] ; then pre-commit run --all-files || ( git diff ; exit 1 ) ; fi
    - if [ "$TEST_CODE" == "true" ] ; then python run_tests.py ; else echo "Testing of the code disabled for this build [log below]" ; fi


